### ISSUE TITLE
btllib fails meson tests on 32-bit archs

### ISSUE THREAD

**Issue by nileshpatra** [bcgsc/btllib#62]
Hi,

btllib fails 7 of its 15 tests on 32-bit archs, build log [here](https://buildd.debian.org/status/fetch.php?pkg=btllib&arch=i386&ver=1.4.9%2Bdfsg-2&stamp=1666621292&raw=0)

I have checked the following:
- It is not a timeout issue, even increasing timeout to 5000s does not work
- It is not a thread related issue, decreasing emulation threads to `1` has no effect.

Would appreciate a fix. Thanks!

**Comment by parham-k** [comment]
Thanks for reporting. I managed to reproduce the issue on a 32-bit Debian 11 VM. SeqReader stalls on 32-bit systems. Minimal code:
```c++
#include <iostream>
#include <btllib/seq_reader.hpp>

int main(int argc, char** argv) {
    btllib::SeqReader reader(argv[1], btllib::SeqReader::Flag::SHORT_MODE);
    for (const auto record : reader)
    	std::cout << record.id << std::endl;
    return 0;
}
```

I'll investigate for a fix.

**Comment by parham-k** [comment]
According to `gdb`, the issue is related to a deadlock happening in [OrderQueueMPMC](https://github.com/bcgsc/btllib/blob/master/include/btllib/order_queue.hpp) on i686 machines. This will require more in-depth debugging, but btllib's Python wrappers don't compile on 32-bit anyway. Therefore, btllib does not support 32-bit systems.
